2022-05-06 21:30:37.984 - INFO - 21284 - azureml.train.automl.automlconfig._start_execution:210 - Submitting remote.
2022-05-06 21:49:20.208 - INFO - 21284 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2022-05-06 21:49:20.232 - INFO - 21284 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2022-05-06 21:49:20.256 - INFO - 21284 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2022-05-06 21:49:23.890 - INFO - 21284 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=3634.32[ms]
2022-05-06 21:49:23.890 - INFO - 21284 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=3658.32[ms]
2022-05-06 21:49:23.891 - INFO - 21284 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2022-05-06 21:49:37.028 - CRITICAL - 21284 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 151, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2022-05-06 21:49:37.029 - WARNING - 21284 - azureml.train.automl._model_download_utilities._download_automl_model:97 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.38.0'. Please install 'azureml-train-automl-runtime==1.38.0' (e.g. `pip install azureml-train-automl-runtime==1.38.0`) and then rerun the previous command.
2022-05-06 21:49:37.041 - INFO - 21284 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=13150.06[ms]
2022-05-06 21:49:37.044 - INFO - 21284 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=16835.43[ms]
